package dev.reva.healthexporter

import androidx.health.connect.client.records.ExerciseSessionRecord

/** Display names for the SDK 1.1 exercise types; preserve unknown future codes. */
internal fun exerciseTypeLabel(type: Int): String = when (type) {
    ExerciseSessionRecord.EXERCISE_TYPE_OTHER_WORKOUT -> "Other workout"
    ExerciseSessionRecord.EXERCISE_TYPE_BADMINTON -> "Badminton"
    ExerciseSessionRecord.EXERCISE_TYPE_BASEBALL -> "Baseball"
    ExerciseSessionRecord.EXERCISE_TYPE_BASKETBALL -> "Basketball"
    ExerciseSessionRecord.EXERCISE_TYPE_BIKING -> "Biking"
    ExerciseSessionRecord.EXERCISE_TYPE_BIKING_STATIONARY -> "Biking stationary"
    ExerciseSessionRecord.EXERCISE_TYPE_BOOT_CAMP -> "Boot camp"
    ExerciseSessionRecord.EXERCISE_TYPE_BOXING -> "Boxing"
    ExerciseSessionRecord.EXERCISE_TYPE_CALISTHENICS -> "Calisthenics"
    ExerciseSessionRecord.EXERCISE_TYPE_CRICKET -> "Cricket"
    ExerciseSessionRecord.EXERCISE_TYPE_DANCING -> "Dancing"
    ExerciseSessionRecord.EXERCISE_TYPE_ELLIPTICAL -> "Elliptical"
    ExerciseSessionRecord.EXERCISE_TYPE_EXERCISE_CLASS -> "Exercise class"
    ExerciseSessionRecord.EXERCISE_TYPE_FENCING -> "Fencing"
    ExerciseSessionRecord.EXERCISE_TYPE_FOOTBALL_AMERICAN -> "Football american"
    ExerciseSessionRecord.EXERCISE_TYPE_FOOTBALL_AUSTRALIAN -> "Football australian"
    ExerciseSessionRecord.EXERCISE_TYPE_FRISBEE_DISC -> "Frisbee disc"
    ExerciseSessionRecord.EXERCISE_TYPE_GOLF -> "Golf"
    ExerciseSessionRecord.EXERCISE_TYPE_GUIDED_BREATHING -> "Guided breathing"
    ExerciseSessionRecord.EXERCISE_TYPE_GYMNASTICS -> "Gymnastics"
    ExerciseSessionRecord.EXERCISE_TYPE_HANDBALL -> "Handball"
    ExerciseSessionRecord.EXERCISE_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING -> "High intensity interval training"
    ExerciseSessionRecord.EXERCISE_TYPE_HIKING -> "Hiking"
    ExerciseSessionRecord.EXERCISE_TYPE_ICE_HOCKEY -> "Ice hockey"
    ExerciseSessionRecord.EXERCISE_TYPE_ICE_SKATING -> "Ice skating"
    ExerciseSessionRecord.EXERCISE_TYPE_MARTIAL_ARTS -> "Martial arts"
    ExerciseSessionRecord.EXERCISE_TYPE_PADDLING -> "Paddling"
    ExerciseSessionRecord.EXERCISE_TYPE_PARAGLIDING -> "Paragliding"
    ExerciseSessionRecord.EXERCISE_TYPE_PILATES -> "Pilates"
    ExerciseSessionRecord.EXERCISE_TYPE_RACQUETBALL -> "Racquetball"
    ExerciseSessionRecord.EXERCISE_TYPE_ROCK_CLIMBING -> "Rock climbing"
    ExerciseSessionRecord.EXERCISE_TYPE_ROLLER_HOCKEY -> "Roller hockey"
    ExerciseSessionRecord.EXERCISE_TYPE_ROWING -> "Rowing"
    ExerciseSessionRecord.EXERCISE_TYPE_ROWING_MACHINE -> "Rowing machine"
    ExerciseSessionRecord.EXERCISE_TYPE_RUGBY -> "Rugby"
    ExerciseSessionRecord.EXERCISE_TYPE_RUNNING -> "Running"
    ExerciseSessionRecord.EXERCISE_TYPE_RUNNING_TREADMILL -> "Running treadmill"
    ExerciseSessionRecord.EXERCISE_TYPE_SAILING -> "Sailing"
    ExerciseSessionRecord.EXERCISE_TYPE_SCUBA_DIVING -> "Scuba diving"
    ExerciseSessionRecord.EXERCISE_TYPE_SKATING -> "Skating"
    ExerciseSessionRecord.EXERCISE_TYPE_SKIING -> "Skiing"
    ExerciseSessionRecord.EXERCISE_TYPE_SNOWBOARDING -> "Snowboarding"
    ExerciseSessionRecord.EXERCISE_TYPE_SNOWSHOEING -> "Snowshoeing"
    ExerciseSessionRecord.EXERCISE_TYPE_SOCCER -> "Soccer"
    ExerciseSessionRecord.EXERCISE_TYPE_SOFTBALL -> "Softball"
    ExerciseSessionRecord.EXERCISE_TYPE_SQUASH -> "Squash"
    ExerciseSessionRecord.EXERCISE_TYPE_STAIR_CLIMBING -> "Stair climbing"
    ExerciseSessionRecord.EXERCISE_TYPE_STAIR_CLIMBING_MACHINE -> "Stair climbing machine"
    ExerciseSessionRecord.EXERCISE_TYPE_STRENGTH_TRAINING -> "Strength training"
    ExerciseSessionRecord.EXERCISE_TYPE_STRETCHING -> "Stretching"
    ExerciseSessionRecord.EXERCISE_TYPE_SURFING -> "Surfing"
    ExerciseSessionRecord.EXERCISE_TYPE_SWIMMING_OPEN_WATER -> "Swimming open water"
    ExerciseSessionRecord.EXERCISE_TYPE_SWIMMING_POOL -> "Swimming pool"
    ExerciseSessionRecord.EXERCISE_TYPE_TABLE_TENNIS -> "Table tennis"
    ExerciseSessionRecord.EXERCISE_TYPE_TENNIS -> "Tennis"
    ExerciseSessionRecord.EXERCISE_TYPE_VOLLEYBALL -> "Volleyball"
    ExerciseSessionRecord.EXERCISE_TYPE_WALKING -> "Walking"
    ExerciseSessionRecord.EXERCISE_TYPE_WATER_POLO -> "Water polo"
    ExerciseSessionRecord.EXERCISE_TYPE_WEIGHTLIFTING -> "Weightlifting"
    ExerciseSessionRecord.EXERCISE_TYPE_WHEELCHAIR -> "Wheelchair"
    ExerciseSessionRecord.EXERCISE_TYPE_YOGA -> "Yoga"
    else -> "Unknown workout"
} + " ($type)"
